server:
  servlet:
    context-path: /demo1
  port: 9999
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdatabase?serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd KK:mm:ss